import { gql } from '@apollo/client'

export const MY_PARTNER_APPLICATION_QUERY = gql`
  query MyPartnerApplication($hospitalCode: HospitalCode!) {
    myPartnerApplication(hospitalCode: $hospitalCode) {
      id
      applicantId
      hospitalCode
      hospitalId
      institutionType
      status
      hospital {
        id
        name
        address
        addressDetail
        phone
        website
        zipCode
        phisCode
        faxNumber
        representative
      }
      isDirector
      directorName
      directorBirthDate
      directorGender
      directorLicenseNo
      directorSchool
      directorGraduationYear
      directorTrainingHospital
      directorDepartment
      directorSubSpecialty
      directorCarNo
      directorPhone
      directorEmail
      directorSmsConsent
      directorEmailConsent
      directorReplyConsent
      staffName
      staffPosition
      staffDeptType
      staffDeptValue
      staffPhone
      staffTel
      staffEmail
      totalBedCount
      activeBedCount
      icuCount
      premiumRoomCount
      multiRoomCount
      erCount
      totalStaffCount
      specialistCount
      nurseCount
      hasIcu
      hasEr
      hasOperatingRoom
      hasPhysicalTherapy
      hasDialysisRoom
      hasHospice
      hasPsychGeneral
      hasPsychClosed
      hasIntegratedNursing
      hasGuardianCare
      hasSharedCare
      isolationRoomCount
      isolationSingleCount
      isolationDoubleCount
      isolationTripleCount
      isolationTypes
      isolationCareType
      isolationRehabType
      hasRehabPt
      hasRehabOt
      hasRehabSt
      hasRehabSwallow
      hasRehabIsolation
      departmentSpecialists
      availableTreatments
      clinicMedicationType
      clinicHasHemodialysis
      clinicHasPeritoneal
      clinicHasPhototherapy
      clinicHasExcimerLaser
      majorEquipment
      remarks
      attachments
      attachmentRows {
        id
        originalName
        storedPath
        mimeType
        fileSize
        createdAt
      }
      rejectReason
      approvedAt
      createdAt
      updatedAt
    }
  }
`

export const MY_PARTNER_APPLICATIONS_QUERY = gql`
  query MyPartnerApplications($pagination: PaginationInput) {
    myPartnerApplications(pagination: $pagination) {
      items {
        id
        hospitalCode
        hospitalId
        institutionType
        status
        hospital {
          id
          name
          address
          phone
          phisCode
        }
        directorName
        staffName
        createdAt
        updatedAt
      }
      totalCount
      hasNextPage
      cursor
    }
  }
`

export const PARTNER_APPLICATION_BY_ID_QUERY = gql`
  query PartnerApplicationById($id: ID!) {
    partnerApplicationById(id: $id) {
      id
      applicantId
      hospitalCode
      hospitalId
      institutionType
      status
      hospital {
        id
        name
        phisCode
        address
        addressDetail
        phone
        zipCode
        faxNumber
        website
        representative
      }
      isDirector
      directorName
      directorBirthDate
      directorGender
      directorLicenseNo
      directorSchool
      directorGraduationYear
      directorTrainingHospital
      directorDepartment
      directorSubSpecialty
      directorCarNo
      directorPhone
      directorEmail
      directorSmsConsent
      directorEmailConsent
      directorReplyConsent
      staffName
      staffPosition
      staffDeptType
      staffDeptValue
      staffPhone
      staffTel
      staffEmail
      totalBedCount
      activeBedCount
      icuCount
      premiumRoomCount
      multiRoomCount
      erCount
      totalStaffCount
      specialistCount
      nurseCount
      hasIcu
      hasEr
      hasOperatingRoom
      hasPhysicalTherapy
      hasDialysisRoom
      hasHospice
      hasPsychGeneral
      hasPsychClosed
      hasIntegratedNursing
      hasGuardianCare
      hasSharedCare
      isolationRoomCount
      isolationSingleCount
      isolationDoubleCount
      isolationTripleCount
      isolationTypes
      isolationCareType
      isolationRehabType
      hasRehabPt
      hasRehabOt
      hasRehabSt
      hasRehabSwallow
      hasRehabIsolation
      departmentSpecialists
      availableTreatments
      clinicMedicationType
      clinicHasHemodialysis
      clinicHasPeritoneal
      clinicHasPhototherapy
      clinicHasExcimerLaser
      majorEquipment
      remarks
      attachments
      attachmentRows {
        id
        originalName
        storedPath
        mimeType
        fileSize
        createdAt
      }
      rejectReason
      reviewedAt
      reviewedById
      approvedAt
      terminatedAt
      createdAt
      updatedAt
    }
  }
`
